new categories format, and other features
inbrainai/sdk-react pull request #26
Opened 2022-12-11 15:39 UTC by MusiikoAS

2022-12-12 08:12 UTC, susslik requested changes
Hey @MusiikoAS - just checked the PR, nice job!
However, I found a few possible improvements and added the comments.
And also the PR destination branch is wrong: It's master instead of develop

2022-12-13 08:27 UTC, MusiikoAS commented on ios/InBrainSurveys.m
> +            return @"SurveyProfileMatchNewSurvey";
done

2022-12-13 08:27 UTC, MusiikoAS commented on ios/InBrainSurveys.m
> +          return @"InBrainSurveyCategoryBeveragesAlcoholic";
done

2022-12-13 08:27 UTC, MusiikoAS commented on ios/InBrainSurveys.m
done

2022-12-13 08:28 UTC, MusiikoAS commented on android/src/main/java/com/inbrain/InBrainSurveysModule.java
> +                            categoryNamed.putString("name", category.name());
created new separated functions for categories and profileMatch maping

2022-12-13 08:28 UTC, MusiikoAS commented on android/src/main/java/com/inbrain/InBrainSurveysModule.java
> +                        WritableMap matches = Arguments.createMap();
created new separated functions for categories and profileMatch maping

2022-12-13 08:29 UTC, MusiikoAS commented on ios/InBrainSurveys.m
> +          break;
done

2022-12-13 08:46 UTC, susslik requested changes
Hey @MusiikoAS - the updates look really great! One small comment was added, could you check it pls when you will have a minute?

2022-12-13 08:46 UTC, susslik commented on android/src/main/java/com/inbrain/InBrainSurveysModule.java
> +                        WritableMap categoryNamed = Arguments.createMap();
If I understood correctly - the "id" and "name" values will be re-written at each "for" interaction. And that variable is used only inside "for" loop - so probably we can move it's declaration inside the loop? Just to keep the local variable only where it needed

2022-12-13 10:52 UTC, susslik approved these changes

2022-12-13 10:52 UTC, merged