2.9.0/sdk improvements part 1
inbrainai/sdk-react pull request #40
Opened 2023-01-13 16:46 UTC by MusiikoAS

2023-01-20 11:20 UTC, susslik requested changes
Hey @MusiikoAS - I've added a few comments, could you check them pls when you're free?

2023-01-20 11:20 UTC, susslik commented on android/src/main/java/com/inbrain/InBrainSurveysModule.java
> -    private HashMap sessionData;
Looks like you forgot about `public void setSessionID(final String sessionId)` and `public void setDataOptions(final ReadableMap data)` methods - they still uses those variables. Please, update the methods.
And do not forget to run the app at both platforms (iOS and Android) to ensure all is fine...

2023-01-21 18:14 UTC, MusiikoAS commented on src/InBrain.tsx
>   * TODO: find any validation library
it's not my commend :)

2023-01-21 18:15 UTC, MusiikoAS commented on src/InBrain.tsx
> + * TODO: find any validation library
it's not my commend :)

2023-01-23 07:48 UTC, susslik commented on src/InBrain.tsx
>   * TODO: find any validation library
I know, looks like this comment was added a looong time ago, however it's useless now

2023-01-23 07:48 UTC, susslik commented on src/InBrain.tsx
> + * TODO: find any validation library
I know, looks like this comment was added a looong time ago, however it's useless now

2023-02-03 12:44 UTC, merged